# [[main]]
#   name = "文章"
#   weight = 10
# [[main]]
#   identifier = "posts"
#   parent = '文章'
#   name = "Posts"
#   pageRef = "posts"
#   weight = 20
[[main]]
  identifier = "archive"
  name = "文章庫"
  pageRef = "archive"
  weight = 30

[[main]]
  name = "作品"
  pageRef = "works"
  weight = 40

# [[main]]
#   name = "其他"
#   weight = 40
# [[main]]
#   identifier = "goods"
#   name = "好物"
#   pageRef = "goods"
#   parent = '其他'
#   weight = 10
# [[main]]
#   identifier = "comments-with-twikoo"
#   name = "Twikoo評論版"
#   url = "https://seven-demo-with-twikoo.netlify.app/"
#   parent = '其他'
#   weight = 20