[[main]]
  name = "文檔"
  pageRef = "docs"
  weight = 10
[[main]]
  name = "部落格"
  pageRef = "posts"
  weight = 20
[[main]]
  name = "歸檔"
  pageRef = "archive"
  weight = 30
[[main]]
  name = "其他"
  weight = 40
[[main]]
  identifier = "goods"
  name = "好物"
  pageRef = "goods"
  parent = '其他'
  weight = 10
[[main]]
  identifier = "comments-with-twikoo"
  name = "Twikoo評論版"
  url = "https://seven-demo-with-twikoo.netlify.app/"
  parent = '其他'
  weight = 20